#!/usr/bin/env python3
"""
Comprehensive French translator: writes a curated FR translation for
every key in Resources/Localizable.xcstrings, regardless of current state.

Run after adding new keys: it overwrites every "fr" entry. Idempotent.

Format strings (%d, %@, %.0f, %lld) are preserved exactly so
NSLocalizedString format calls keep working.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PATH = ROOT / "Resources" / "Localizable.xcstrings"

FR: dict[str, str] = {
    # === actions / generics ===
    "action.cancel": "Annuler",
    "action.delete": "Supprimer",
    "action.done": "Terminé",
    "action.edit": "Modifier",
    "action.ok": "OK",
    "action.save": "Enregistrer",
    "action.saved": "Enregistré",
    "action.saving": "Enregistrement…",
    "action.search": "Rechercher",
    "action.start_class": "Démarrer le cours",

    # === admin ===
    "admin.account_created": "Compte créé",
    "admin.account_details": "Détails du compte",
    "admin.accounts": "Comptes",
    "admin.branch": "Branche",
    "admin.create": "Créer",
    "admin.create_account": "Créer un compte",
    "admin.no_branch": "Aucune branche",
    "admin.role": "Rôle",
    "admin.role_assignment": "Attribution de rôle",

    # === age groups ===
    "age.cadets": "Cadets",
    "age.cubs": "Poussins",
    "age.juniors": "Juniors",
    "age.kids": "Enfants",
    "age.seniors": "Séniors",

    # === announcements ===
    "announcement.audience": "Audience",
    "announcement.audience.all": "Tout le monde",
    "announcement.audience.athletes": "Athlètes",
    "announcement.audience.branchManagers": "Responsables de branche",
    "announcement.audience.coaches": "Entraîneurs",
    "announcement.audience.parents": "Parents",
    "announcement.body_ar": "Corps (arabe)",
    "announcement.body_en": "Corps (anglais)",
    "announcement.compose": "Rédiger",
    "announcement.requires_rsvp": "Réponse requise",
    "announcement.rsvp.maybe": "Peut-être",
    "announcement.rsvp.no": "Non",
    "announcement.rsvp.yes": "Oui",
    "announcement.rsvp_deadline": "Date limite de réponse",
    "announcement.title_ar": "Titre (arabe)",
    "announcement.title_en": "Titre (anglais)",

    # === assessment / technical ===
    "assessment.accuracy": "Précision",
    "assessment.add": "Technique",
    "assessment.balance": "Équilibre",
    "assessment.entry": "Évaluation technique",
    "assessment.expression": "Expression",
    "assessment.poomsae_form": "Forme poomsae",
    "assessment.power": "Puissance",
    "assessment.rhythm": "Rythme",

    # === athlete ===
    "athlete.add": "Ajouter un athlète",
    "athlete.add_emergency": "Ajouter un contact d'urgence",
    "athlete.allergies": "Allergies",
    "athlete.allergies_placeholder": "séparées par virgule, ex. arachides, latex",
    "athlete.belt_color": "Couleur de ceinture",
    "athlete.belt_kind": "Type de ceinture",
    "athlete.belt_number": "Numéro de ceinture",
    "athlete.blood_type": "Groupe sanguin",
    "athlete.complete_profile": "Compléter le profil",
    "athlete.date_of_birth": "Date de naissance",
    "athlete.dominant_stance": "Garde dominante",
    "athlete.edit": "Modifier l'athlète",
    "athlete.emergency_contact": "Contact d'urgence",
    "athlete.emergency_name": "Nom",
    "athlete.emergency_phone": "Téléphone",
    "athlete.emergency_relationship": "Lien de parenté",
    "athlete.emirates_id": "Carte d'identité émiratie",
    "athlete.emirates_id_format": "Format : 784-AAAA-NNNNNNN-N",
    "athlete.error_no_branch": "Aucune branche disponible. Veuillez d'abord ajouter une branche.",
    "athlete.federation_licence": "N° de licence fédérale",
    "athlete.fit_to_train": "Apte à l'entraînement",
    "athlete.gender": "Sexe",
    "athlete.gender.female": "Fille",
    "athlete.gender.male": "Garçon",
    "athlete.height": "Taille",
    "athlete.identity": "Identité",
    "athlete.image_rights": "Consentement droit à l'image",
    "athlete.import": "Importer",
    "athlete.import.choose_file": "Choisir un fichier CSV…",
    "athlete.import.download_template": "Obtenir le modèle",
    "athlete.import.empty_file": "Le fichier est vide",
    "athlete.import.instructions": "Import groupé depuis un tableur",
    "athlete.import.instructions_body": "Touchez « Obtenir le modèle » pour enregistrer le CSV depuis l'application, complétez-le (un athlète par ligne), puis revenez ici et choisissez le fichier. Excel et Numbers exportent en CSV en un clic.",
    "athlete.import.loading_lookups": "Chargement des branches et entraîneurs…",
    "athlete.import.lookups_ready": "%d branches et %d entraîneurs prêts",
    "athlete.import.progress": "Importé %d sur %d…",
    "athlete.import.skipped_header": "Lignes ignorées",
    "athlete.import.summary": "%d importés · %d ignorés",
    "athlete.import.template_hint": "Le modèle est intégré à l'application — pas besoin de télécharger depuis le dépôt.",
    "athlete.joined_at": "Inscrit le",
    "athlete.kyorugi_tier": "Niveau kyorugi",
    "athlete.medical_conditions": "Conditions médicales",
    "athlete.medical_conditions_placeholder": "séparées par virgule, ex. asthme",
    "athlete.medications": "Médicaments",
    "athlete.medications_placeholder": "séparés par virgule",
    "athlete.member_number": "Numéro de membre",
    "athlete.member_number_help": "Attribué automatiquement. Unique à vie — jamais réutilisé même si l'athlète est retiré.",
    "athlete.member_number_pending": "attribué à l'enregistrement",
    "athlete.missing.blood_type": "Groupe sanguin",
    "athlete.missing.emergency_contact": "Au moins un contact d'urgence",
    "athlete.missing.federation_licence": "Numéro de licence fédérale",
    "athlete.missing.height": "Taille",
    "athlete.missing.id_document": "Carte d'identité émiratie ou numéro de passeport",
    "athlete.missing.image_rights": "Consentement droit à l'image",
    "athlete.missing.photo": "Photo de profil",
    "athlete.missing.school": "École",
    "athlete.missing.travel_permission": "Autorisation de voyage",
    "athlete.nationality": "Nationalité",
    "athlete.no_emergency_contacts_yet": "Aucun contact d'urgence",
    "athlete.passport_number": "Numéro de passeport",
    "athlete.placement": "Classement",
    "athlete.poomsae_syllabus": "Programme poomsae",
    "athlete.profile_completeness": "%d%% complet · %d champ(s) manquant(s)",
    "athlete.profile_incomplete": "Profil incomplet",
    "athlete.save_error": "Erreur d'enregistrement",
    "athlete.school": "École",
    "athlete.section.family": "Famille et consentement",
    "athlete.section.identity": "Identité",
    "athlete.section.medical": "Médical",
    "athlete.section.technical": "Technique",
    "athlete.status": "Statut",
    "athlete.travel_permission": "Autorisation de voyage",

    # === attendance ===
    "attendance.absent": "Absent",
    "attendance.excused": "Excusé",
    "attendance.late": "En retard",
    "attendance.present": "Présent",

    # === audit ===
    "audit.action": "Action",
    "audit.actor": "Auteur",
    "audit.since": "Depuis",
    "audit.target": "Cible",
    "audit.timestamp": "Heure",
    "audit.title": "Journal d'audit",

    # === auth ===
    "auth.add_child": "Ajouter un enfant",
    "auth.child_member_numbers": "Numéros de membre des enfants",
    "auth.child_member_numbers_hint": "Saisissez le numéro de membre de votre enfant (1001 à 1999)",
    "auth.confirm_password": "Confirmer le mot de passe",
    "auth.create_account": "Créer un compte",
    "auth.email": "E-mail",
    "auth.error.invalid_member_number": "Saisissez un numéro de membre valide",
    "auth.error.member_not_found": "Aucun athlète trouvé pour ce numéro",
    "auth.error.member_number_range": "Le numéro doit être entre 1001 et 1999",
    "auth.full_name": "Nom complet",
    "auth.full_name_ar": "Nom complet (arabe)",
    "auth.invalid_credential": "Identifiants invalides.",
    "auth.member_number_placeholder": "ex. 1001",
    "auth.parent_info": "Informations parent",
    "auth.parent_prompt": "Êtes-vous parent ?",
    "auth.parent_sign_up": "Inscription parent",
    "auth.password": "Mot de passe",
    "auth.role_claim_help": "Dites-nous qui vous êtes. Un administrateur examinera et approuvera avant l'accès.",
    "auth.role_claim_intro": "Presque terminé",
    "auth.role_claim_title": "Revendiquer votre rôle",
    "auth.sign_in": "Se connecter",
    "auth.signing_in": "Connexion…",
    "auth.submit_for_review": "Soumettre pour validation",
    "auth.subtitle": "Connectez-vous pour accéder à votre tableau de bord.",
    "auth.use_demo_session": "Utiliser une session de démo (hors ligne)",
    "auth.use_email": "Utiliser un e-mail",
    "auth.welcome": "Bienvenue chez SHJSDSC",

    # === belts ===
    "belt.black": "Noire",
    "belt.blue": "Bleue",
    "belt.dan": "Dan",
    "belt.dan.1": "1er Dan",
    "belt.dan.2": "2e Dan",
    "belt.dan.3": "3e Dan",
    "belt.dan.4": "4e Dan",
    "belt.dan.5": "5e Dan",
    "belt.dan.6": "6e Dan",
    "belt.dan.7": "7e Dan",
    "belt.dan.8": "8e Dan",
    "belt.dan.9": "9e Dan",
    "belt.green": "Verte",
    "belt.gup": "Gup",
    "belt.gup.1": "Rouge 1er gup",
    "belt.gup.10": "Blanche 10e gup",
    "belt.gup.2": "Rouge 2e gup",
    "belt.gup.3": "Bleue 3e gup",
    "belt.gup.4": "Bleue 4e gup",
    "belt.gup.5": "Verte 5e gup",
    "belt.gup.6": "Verte 6e gup",
    "belt.gup.7": "Jaune 7e gup",
    "belt.gup.8": "Jaune 8e gup",
    "belt.gup.9": "Blanche 9e gup",
    "belt.poom": "Poom",
    "belt.poom.1": "1er Poom",
    "belt.poom.2": "2e Poom",
    "belt.poom.3": "3e Poom",
    "belt.poom.4": "4e Poom",
    "belt.red": "Rouge",
    "belt.white": "Blanche",
    "belt.yellow": "Jaune",

    # === branch ===
    "branch.about": "À propos",
    "branch.achievements": "Réussites",
    "branch.add": "Ajouter une branche",
    "branch.address": "Adresse",
    "branch.address_ar": "Adresse (arabe)",
    "branch.area": "Zone",
    "branch.brand_color": "Couleur de marque (hex)",
    "branch.brand_color_hint": "Hex tel que #E24B4A — utilisé pour les cartes et en-têtes.",
    "branch.branding": "Identité visuelle",
    "branch.capacity": "Capacité",
    "branch.closed_now": "Fermé",
    "branch.closes_at": "Ferme à",
    "branch.coaches": "Entraîneurs",
    "branch.code": "Code",
    "branch.connect": "Liens",
    "branch.directions": "Itinéraire",
    "branch.distance_km": "À %.1f km",
    "branch.distance_m": "À %d m",
    "branch.email": "E-mail",
    "branch.facility": "Installation",
    "branch.focus": "Spécialité",
    "branch.founded": "Fondée",
    "branch.holiday_closures": "Fermetures à venir",
    "branch.hours": "Horaires d'ouverture",
    "branch.latitude": "Latitude",
    "branch.longitude": "Longitude",
    "branch.open_now": "Ouvert",
    "branch.opens_at": "Ouvre à",
    "branch.phone": "Téléphone",
    "branch.pricing": "Tarifs",
    "branch.profile": "Profil de la branche",
    "branch.programs": "Programmes",
    "branch.ramadan_hours": "Horaires de Ramadan",
    "branch.save_error": "Impossible d'enregistrer la branche",
    "branch.see_promotions": "Voir les promotions",
    "branch.tab.compliance": "Conformité",
    "branch.tab.facility": "Installation",
    "branch.tab.financials": "Finances",
    "branch.tab.hours": "Horaires",
    "branch.tab.identity": "Identité",
    "branch.tab.inventory": "Inventaire",
    "branch.tab.media": "Médias",
    "branch.tab.milestones": "Étapes",
    "branch.tab.pricing": "Tarifs",
    "branch.tab.programs": "Programmes",
    "branch.tab.safeguarding": "Protection",
    "branch.tab.social": "Social",
    "branch.tagline_ar": "Slogan (arabe)",
    "branch.tagline_en": "Slogan (anglais)",
    "branch.visit": "Visiter",

    # === certifications ===
    "cert.doping": "Antidopage",
    "cert.expired": "Expirée",
    "cert.expiring": "Expire bientôt",
    "cert.firstAid": "Secourisme",
    "cert.new_expiry": "Nouvelle expiration",
    "cert.ok": "À jour",
    "cert.refereeing": "Arbitrage",
    "cert.renew": "Renouveler",
    "cert.safeguarding": "Protection",
    "cert.severity.expired": "Expirée",
    "cert.severity.expiring": "Expire bientôt",
    "cert.severity.ok": "OK",
    "cert.wtCoaching": "Entraîneur WT",
    "certs.expired": "Certifications expirées",

    # === chart trends ===
    "chart.physical_trend": "Tendance physique",
    "chart.technical_trend": "Tendance technique",
    "chart.wellness_trend": "Tendance bien-être",

    # === coach ===
    "coach.add": "Ajouter un entraîneur",
    "coach.anti_doping_expiry": "Expiration antidopage",
    "coach.athletes_managed": "Athlètes encadrés",
    "coach.athletes_promoted_year": "Promus (cette année)",
    "coach.bio": "Biographie",
    "coach.bio_ar": "Biographie (arabe)",
    "coach.bio_placeholder": "Quelques phrases sur le parcours de l'entraîneur",
    "coach.classes_this_week": "Cours cette semaine",
    "coach.complete_profile": "Compléter le profil",
    "coach.contract_type": "Type de contrat",
    "coach.cpd_hours": "Heures de FPC",
    "coach.cpd_hours_hint": "Formation professionnelle continue suivie cette année",
    "coach.dan_rank": "Rang Dan",
    "coach.edit": "Modifier l'entraîneur",
    "coach.first_aid_expiry": "Expiration secourisme",
    "coach.hired_at": "Date d'embauche",
    "coach.kukkiwon_cert": "Certificat Kukkiwon",
    "coach.kukkiwon_issued": "Date d'émission Kukkiwon",
    "coach.kyorugi_referee": "Arbitre kyorugi",
    "coach.kyorugi_referee_expiry": "Expiration arbitre kyorugi",
    "coach.kyorugi_referee_level": "Niveau arbitre kyorugi",
    "coach.medals_this_year": "Médailles (cette année)",
    "coach.missing.anti_doping": "Certificat antidopage",
    "coach.missing.bio": "Biographie de l'entraîneur",
    "coach.missing.kukkiwon": "Certificat Kukkiwon",
    "coach.missing.kyorugi_referee": "Licence d'arbitre kyorugi",
    "coach.missing.photo": "Photo de profil",
    "coach.missing.poomsae_referee": "Licence d'arbitre poomsae",
    "coach.missing.weekly_hours": "Heures contractuelles hebdomadaires",
    "coach.missing.wt_licence_expiry": "Expiration licence WT",
    "coach.not_set": "Non défini",
    "coach.on_call": "Sur appel",
    "coach.on_call_short": "Sur appel",
    "coach.parent_satisfaction": "Satisfaction parents",
    "coach.peer_review": "Évaluation par pairs",
    "coach.poomsae_referee": "Arbitre poomsae",
    "coach.poomsae_referee_expiry": "Expiration arbitre poomsae",
    "coach.poomsae_referee_level": "Niveau arbitre poomsae",
    "coach.primary_branch": "Branche principale",
    "coach.profile_completeness": "%d%% complet · %d champ(s) manquant(s)",
    "coach.profile_incomplete": "Profil incomplet",
    "coach.safeguarding_expiry": "Expiration protection",
    "coach.save_error": "Erreur d'enregistrement",
    "coach.secondary_branches": "Branches secondaires",
    "coach.secondary_branches_hint": "Branches que cet entraîneur couvre en plus de sa branche principale",
    "coach.section.assignment": "Affectation",
    "coach.section.credentials": "Diplômes",
    "coach.section.identity": "Identité",
    "coach.section.performance": "Performance",
    "coach.set_date": "Définir la date",
    "coach.set_rating": "Définir la note",
    "coach.weekly_hours": "Heures hebdomadaires",
    "coach.wt_coach_licence": "Licence d'entraîneur WT",
    "coach.wt_coach_licence_expiry": "Expiration licence WT",
    "coach.wt_coach_licence_level": "Niveau licence WT",

    # === compliance ===
    "compliance.aed": "DEA sur place",
    "compliance.civil_defence": "Certificat Défense civile",
    "compliance.emergency_plan": "Revue plan d'urgence",
    "compliance.expired": "Expiré",
    "compliance.expires_on": "Expire le",
    "compliance.expiring": "Expire bientôt",
    "compliance.first_aid_kit": "Trousse de secours",
    "compliance.health_safety": "Inspection santé et sécurité",
    "compliance.insurance": "Assurance",
    "compliance.ok": "OK",
    "compliance.sports_council": "Conseil sportif de Sharjah",

    # === contract types ===
    "contract.contractor": "Contractuel",
    "contract.fullTime": "Temps plein",
    "contract.partTime": "Temps partiel",

    # === days ===
    "day.fri": "Ven",
    "day.mon": "Lun",
    "day.sat": "Sam",
    "day.sun": "Dim",
    "day.thu": "Jeu",
    "day.tue": "Mar",
    "day.wed": "Mer",

    # === KPI dimensions ===
    "dimension.adherence": "Assid",
    "dimension.belt_progression": "Progr",
    "dimension.competition": "Comp",
    "dimension.physical": "Phys",
    "dimension.technical": "Tech",
    "dimension.wellness": "Bien-être",

    # === disciplines ===
    "discipline.competition": "Compétition",
    "discipline.fitness": "Fitness",
    "discipline.fundamentals": "Bases",
    "discipline.kyorugi": "Combat",
    "discipline.poomsae": "Poomsae",

    # === empty states ===
    "empty.no_announcements": "Aucune annonce",
    "empty.no_athletes_flagged": "Aucun athlète signalé",
    "empty.no_brackets": "Aucun tableau généré",
    "empty.no_certifications": "Aucune certification",
    "empty.no_classes_today": "Aucun cours aujourd'hui",
    "empty.no_coaches": "Aucun entraîneur",
    "empty.no_data": "Aucune donnée",
    "empty.no_linked_athletes": "Aucun athlète lié",
    "empty.no_matches_yet": "Aucun match encore",
    "empty.no_registrations": "Aucune inscription",
    "empty.no_sessions": "Aucune session de passage",
    "empty.no_tournaments": "Aucun tournoi",
    "empty.nobody_to_grade": "Personne à évaluer",
    "empty.search_no_results": "Aucun résultat",

    # === export ===
    "export.csv": "Exporter en CSV",
    "export.pdf": "Exporter en PDF",
    "export.share": "Partager",

    # === facility ===
    "facility.ac": "Climatisation",
    "facility.changing_rooms": "Vestiaires",
    "facility.competition_grade": "Niveau compétition",
    "facility.floor_area": "Surface",
    "facility.halls": "Salles",
    "facility.mirror_walls": "Murs miroirs",
    "facility.parking": "Parking",
    "facility.prayer_room": "Salle de prière",
    "facility.pss": "PSS",
    "facility.pss_brand": "Marque PSS",
    "facility.scoreboard": "Tableau d'affichage",
    "facility.sound_system": "Système audio",
    "facility.spectator_seats": "Sièges spectateurs",
    "facility.wudu": "Ablutions",

    # === federation ===
    "federation.clubInternal": "Interne au club",
    "federation.gcc": "CCG",
    "federation.uae": "Fédération EAU",
    "federation.wtf": "World Taekwondo",

    # === filter ===
    "filter.all": "Tous",
    "filter.none": "Aucun",
    "filter.title": "Filtrer",

    # === financials ===
    "financials.equipment": "Équipement",
    "financials.expenses": "Dépenses",
    "financials.marketing": "Marketing",
    "financials.month": "Mois",
    "financials.net": "Net",
    "financials.other": "Autre",
    "financials.outstanding": "Frais impayés",
    "financials.payment_plans": "Plans de paiement",
    "financials.rent": "Loyer",
    "financials.revenue": "Revenu",
    "financials.staff_cost": "Coût du personnel",
    "financials.utilities": "Charges",

    # === find a branch ===
    "find_branch.subtitle": "Découvrez les dojangs SSDSC près de chez vous.",
    "find_branch.title": "Trouver une branche",

    # === grading ===
    "grading.awarded_to": "Décerné à",
    "grading.blocking.attendance": "Présence inférieure à 75 %",
    "grading.blocking.months_at_rank": "Temps insuffisant au grade actuel",
    "grading.blocking.physical": "Composite physique inférieur à 60",
    "grading.blocking.technical": "Moyenne technique inférieure à 6,5",
    "grading.breaking_score": "Casse",
    "grading.candidates": "Candidats",
    "grading.certificate": "Certificat",
    "grading.dashboard": "Examens",
    "grading.decision": "Décision",
    "grading.decision.fail": "Échec",
    "grading.decision.pass": "Réussi",
    "grading.decision.retry": "À repasser",
    "grading.eligibility": "Éligibilité",
    "grading.eligible": "Éligible",
    "grading.examiners": "Examinateurs",
    "grading.from_belt": "Depuis",
    "grading.hijri_date": "Date hégirienne",
    "grading.issued_on": "Délivré le",
    "grading.kibon_score": "Kibon",
    "grading.kyorugi_score": "Kyorugi",
    "grading.not_eligible": "Pas encore éligible",
    "grading.poomsae_score": "Poomsae",
    "grading.schedule": "Programmer un passage",
    "grading.scheduled_at": "Programmé le",
    "grading.score": "Note",
    "grading.scored": "noté",
    "grading.session": "Session de passage",
    "grading.signed_by": "Signé par",
    "grading.status.cancelled": "Annulée",
    "grading.status.completed": "Terminée",
    "grading.status.inProgress": "En cours",
    "grading.status.scheduled": "Programmée",
    "grading.to_belt": "Vers",

    # === greetings ===
    "greeting.hi": "Bonjour,",
    "greeting.morning": "Sabah al-khair,",

    # === headings ===
    "heading.active_athletes": "Athlètes actifs",
    "heading.athletes": "Athlètes",
    "heading.belt_journey": "Parcours des ceintures",
    "heading.branch_grades": "Notes par branche",
    "heading.branches": "Branches",
    "heading.classes": "Cours",
    "heading.club_composite": "Composite du club",
    "heading.coaches": "Entraîneurs",
    "heading.composite": "Composite",
    "heading.entries": "Ajouter une entrée",
    "heading.medals_ytd": "Médailles cette année",
    "heading.my_athletes": "Mes athlètes",
    "heading.next_class": "Prochain cours",
    "heading.performance_trend": "Tendance de performance",
    "heading.ready_to_grade": "Prêts à passer le grade",
    "heading.recent_matches": "Matchs récents",
    "heading.today": "Aujourd'hui",
    "heading.upcoming_sessions": "Sessions à venir",
    "heading.utilisation": "Utilisation",
    "heading.watch_list": "Liste de surveillance",

    # === inventory ===
    "inventory.aed": "DEA",
    "inventory.beltStock": "Stock de ceintures",
    "inventory.breakingBoard": "Planche de casse",
    "inventory.condition_fair": "Moyen",
    "inventory.condition_good": "Bon",
    "inventory.condition_poor": "Mauvais",
    "inventory.doboK": "Dobok",
    "inventory.forearmGuard": "Protège-avant-bras",
    "inventory.groinGuard": "Protège-aine",
    "inventory.helmet": "Casque",
    "inventory.hogu": "Plastron (hogu)",
    "inventory.kickingPad": "Bouclier de frappe",
    "inventory.last_audit": "Dernier audit",
    "inventory.mat": "Tapis",
    "inventory.medkit": "Trousse de secours",
    "inventory.mouthGuard": "Protège-dents",
    "inventory.other": "Autre",
    "inventory.scoreboard": "Tableau d'affichage",
    "inventory.shinGuard": "Protège-tibia",
    "inventory.targetPad": "Cible",

    # === KPI ===
    "kpi.active_athletes": "Athlètes actifs",
    "kpi.branches": "Branches",
    "kpi.composite": "Composite",
    "kpi.medals": "Médailles",
    "kpi.weight": "Poids",
    "kpi.win_rate": "Taux de victoire",

    # === kyorugi tier ===
    "kyorugi_tier.competitive": "Compétitif",
    "kyorugi_tier.elite": "Élite",
    "kyorugi_tier.recreational": "Loisir",

    # === language picker ===
    "language.arabic": "العربية",
    "language.english": "English",
    "language.french": "Français",
    "language.system": "Système",

    # === manager dashboard ===
    "manager.add_item": "Ajouter un élément",
    "manager.add_milestone": "Ajouter une étape",
    "manager.add_month": "Ajouter un mois",
    "manager.add_program": "Ajouter un programme",
    "manager.alerts": "Alertes",
    "manager.compose_announcement": "Rédiger une annonce",
    "manager.dashboard": "Tableau de bord",
    "manager.edit_programs": "Modifier les programmes",
    "manager.gallery_urls": "URL de la galerie",
    "manager.hero_url": "URL de la photo principale",
    "manager.kpi.active": "Actifs",
    "manager.kpi.coaches_on_duty": "Entraîneurs présents",
    "manager.kpi.compliance": "Conformité",
    "manager.kpi.registered": "Inscrits",
    "manager.kpi.sessions_today": "Séances aujourd'hui",
    "manager.kpi.utilisation": "Utilisation",
    "manager.log_financials": "Saisir la finance",
    "manager.logo_url": "URL du logo",
    "manager.media_url_hint": "L'étape 5 remplacera les URL par des téléversements de photos.",
    "manager.no_activity": "Aucune activité récente.",
    "manager.no_alerts": "Aucune alerte active.",
    "manager.quick_actions": "Actions rapides",
    "manager.recent_activity": "Activité récente",
    "manager.update_inventory": "Mettre à jour l'inventaire",
    "manager.video_url": "URL de la visite vidéo",
    "manager.view_attendance": "Voir la présence",
    "manager.watch_list": "Liste de surveillance",

    # === match (live scoring) ===
    "match.action.body_kick": "Corps",
    "match.action.head_kick": "Tête",
    "match.action.penalty": "Pénalité",
    "match.action.punch": "Poing",
    "match.action.turn_body": "Retourné corps",
    "match.action.turn_head": "Retourné tête",
    "match.chung": "Chung",
    "match.confirm": "Confirmer",
    "match.draw": "Match nul",
    "match.end_round": "Fin de round",
    "match.event_log": "Journal des événements",
    "match.hong": "Hong",
    "match.live": "Match en direct",
    "match.practice": "Match d'entraînement",
    "match.round": "Round",
    "match.start_round": "Round suivant",
    "match.summary": "Résumé du match",
    "match.time_remaining": "Temps",
    "match.winner": "Vainqueur",

    # === medals ===
    "medal.bronze": "Bronze",
    "medal.gold": "Or",
    "medal.none": "Aucune",
    "medal.silver": "Argent",

    # === milestones ===
    "milestone.alumniAchievement": "Réussite d'un ancien",
    "milestone.championshipWon": "Championnat",
    "milestone.founded": "Fondation",
    "milestone.partnership": "Partenariat",
    "milestone.recordSet": "Record établi",
    "milestone.renovation": "Rénovation",
    "milestone.staffMilestone": "Étape équipe",

    # === notifications ===
    "notif.cert_expiring.body": "%@ expire dans %d jours.",
    "notif.cert_expiring.title": "Certification arrivant à expiration",
    "notif.history": "Historique",
    "notif.history_empty": "L'historique des notifications est conservé par le système.",
    "notif.kind.attendanceReminder": "Rappel de présence",
    "notif.kind.certExpiring": "Expiration de certification",
    "notif.kind.gradingScheduled": "Passage de grade programmé",
    "notif.kind.liveMatchAlert": "Alerte de match en direct",
    "notif.kind.tdSundayDigest": "Résumé du dimanche",
    "notif.kind.tournamentRegistration": "Inscription au tournoi",
    "notif.preferences": "Préférences",
    "notif.sunday_digest.body": "Composite du club %.0f · %d à surveiller · %d certifs expirent",
    "notif.sunday_digest.body_test": "Tir d'essai — votre résumé hebdomadaire ressemblera à ceci.",
    "notif.sunday_digest.title": "Résumé hebdomadaire SHJSDSC",

    # === permissions ===
    "permission.denied": "Vous n'avez pas la permission pour cette action.",

    # === photo ===
    "photo.idle": "Choisissez une image à téléverser.",
    "photo.load_failed": "Impossible de charger l'image.",
    "photo.pick": "Choisir une photo",
    "photo.uploaded": "Téléversée",

    # === physical tests ===
    "physical.add": "Physique",
    "physical.agility": "Agilité 4×10",
    "physical.beep_test": "Bip-test (palier)",
    "physical.entry": "Test physique",
    "physical.help": "Des temps plus courts en sprint et agilité sont meilleurs.",
    "physical.notes": "Notes",
    "physical.push_ups": "Pompes / min",
    "physical.sprint_30m": "Sprint 30 m",
    "physical.vertical_jump": "Saut vertical",

    # === pomodoro ===
    "pomodoro.add_group": "Ajouter un groupe",
    "pomodoro.add_rest": "Ajouter repos",
    "pomodoro.add_work": "Ajouter travail",
    "pomodoro.edit": "Modifier l'exercice",
    "pomodoro.elapsed": "Écoulé",
    "pomodoro.empty.body": "Créez un exercice, définissez les intervalles de travail et de repos, groupez les rounds, puis lancez-le en cours.",
    "pomodoro.empty.title": "Aucun exercice",
    "pomodoro.end": "Fin",
    "pomodoro.finished": "Terminé",
    "pomodoro.group": "Groupe",
    "pomodoro.idle": "Prêt",
    "pomodoro.name": "Nom",
    "pomodoro.new": "Nouvel exercice",
    "pomodoro.pause": "Pause",
    "pomodoro.remove_last_group": "Supprimer le dernier groupe",
    "pomodoro.repetitions": "Répétitions",
    "pomodoro.rest": "Repos",
    "pomodoro.resume": "Reprendre",
    "pomodoro.round": "Round",
    "pomodoro.session": "Session",
    "pomodoro.session_n %lld": "Session %lld",
    "pomodoro.skip": "Suivant",
    "pomodoro.tab": "Minuteur",
    "pomodoro.title": "Minuteurs d'exercice",
    "pomodoro.transition": "Sifflet",
    "pomodoro.whistle": "Durée du sifflet",
    "pomodoro.whistle.hint": "1 à 5 secondes. Joué à chaque transition.",
    "pomodoro.work": "Travail",

    # === program / pricing ===
    "program.age_range": "Tranche d'âge",
    "program.annual_prepay": "Paiement annuel : %d%%",
    "program.equipment_package": "Pack équipement",
    "program.monthly_fee": "Cotisation mensuelle",
    "program.registration_fee": "Inscription",
    "program.schedule": "Calendrier",
    "program.sibling_discount": "Remise fratrie : %d%%",
    "program.trial_class": "Cours d'essai",
    "program.women_only": "Femmes uniquement",

    # === registration ===
    "registration.disqualified": "Disqualifié",
    "registration.registered": "Inscrit",
    "registration.weighedIn": "Pesé",
    "registration.withdrawn": "Retiré",

    # === roles ===
    "role.admin": "Administrateur",
    "role.analyst": "Analyste",
    "role.athlete": "Athlète",
    "role.branchManager": "Responsable de branche",
    "role.coach": "Entraîneur",
    "role.developer": "Développeur",
    "role.parent": "Parent",
    "role.technicalDirector": "Directeur technique",

    # === safeguarding ===
    "safeguarding.last_training": "Dernière formation équipe",
    "safeguarding.officer": "Responsable protection",
    "safeguarding.policy_url": "URL document de politique",

    # === score / live match actions ===
    "score.bodyKick": "Coup de pied corps",
    "score.headKick": "Coup de pied tête",
    "score.penalty": "Pénalité",
    "score.punch": "Coup de poing",
    "score.turnBodyKick": "Coup retourné corps",
    "score.turnHeadKick": "Coup retourné tête",

    # === settings ===
    "settings.about": "À propos",
    "settings.developer": "Développeur",
    "settings.export_data": "Exporter mes données",
    "settings.fire_test": "Tester l'envoi du résumé",
    "settings.language": "Langue",
    "settings.manage": "Gérer",
    "settings.notifications": "Notifications",
    "settings.privacy": "Confidentialité",
    "settings.role": "Changer de rôle",
    "settings.sign_out": "Se déconnecter",
    "settings.title": "Paramètres",
    "settings.use_demo_data": "Utiliser des données de démo",
    "settings.use_demo_data_help": "Redémarrez l'application après modification. Force le DemoRepository hors ligne pour itérer l'UI sans Supabase.",
    "settings.wipe_local": "Effacer les données locales",
    "settings.wipe_local_help": "Annule les notifications, oublie l'utilisateur, supprime les photos en cache et déconnecte. Forcez la fermeture puis rouvrez pour changer de backend.",

    # === social ===
    "social.instagram": "Instagram",
    "social.tiktok": "TikTok",
    "social.website": "Site web",
    "social.whatsapp_athletes": "WhatsApp (athlètes)",
    "social.whatsapp_parents": "WhatsApp (parents)",
    "social.youtube": "YouTube",

    # === stance ===
    "stance.orthodox": "Orthodoxe",
    "stance.southpaw": "Gaucher",
    "stance.switchStance": "Changeante",

    # === athlete status ===
    "status.active": "Actif",
    "status.competitionTeam": "Équipe compét.",
    "status.readyToGrade": "Prêt à passer",
    "status.rest": "Repos",
    "status.watch": "Surveiller",

    # === tabs ===
    "tab.announcements": "Annonces",
    "tab.athletes": "Athlètes",
    "tab.branches": "Branches",
    "tab.certifications": "Certifications",
    "tab.classes": "Cours",
    "tab.coaches": "Entraîneurs",
    "tab.grading": "Examens",
    "tab.home": "Accueil",
    "tab.more": "Plus",
    "tab.overview": "Aperçu",
    "tab.people": "Personnes",
    "tab.profile": "Profil",
    "tab.schedule": "Planning",
    "tab.tournaments": "Tournois",

    # === tournaments ===
    "tournament.bracket": "Tableau",
    "tournament.generate_bracket": "Générer le tableau",
    "tournament.official": "Tournoi officiel",
    "tournament.past": "Passés",
    "tournament.register": "Inscrire",
    "tournament.seed": "Tête de série",
    "tournament.upcoming": "À venir",
    "tournament.weigh_in": "Pesée",
    "tournament.weight_category": "Catégorie de poids",

    # === trends ===
    "trend.180": "180 j",
    "trend.30": "30 j",
    "trend.90": "90 j",

    # === weight cut ===
    "weightcut.current": "Actuel",
    "weightcut.days_left": "Jours avant compét.",
    "weightcut.delta": "Delta",
    "weightcut.target": "Objectif",

    # === wellness ===
    "wellness.add": "Bien-être",
    "wellness.entry": "Pointage bien-être",
    "wellness.mood": "Humeur",
    "wellness.rpe": "RPE dernière séance",
    "wellness.sleep_hours": "Heures de sommeil",
    "wellness.soreness": "Courbatures",
    "wellness.streak": "Série de jours",

    # === lone keys (placeholder strings used as keys) ===
    "category": "catégorie",
    "certificate number": "numéro de certificat",
    "date": "date",
    "expenses": "dépenses",
    "kg": "kg",
    "month": "mois",
    "name": "nom",
    "one per line": "un par ligne",
    "policy": "politique",
    "provider": "fournisseur",
    "revenue": "revenu",
    "target": "cible",
    "title (ar)": "titre (ar)",
    "title (en)": "titre (en)",
    "value": "valeur",
}

# Keys whose value is a literal symbol/URL/placeholder — same in FR.
LITERAL_KEYS = {
    "", "@handle", "#E24B4A", "+971 6 555 0000", "06:00", "16:00", "17:00",
    "23:00", "25.346", "55.420", "784-0000-0000000-0", "BR-X",
    "Daedo / KP&P", "WhatsApp", "branch@ssdsc.ae", "https://",
    "https://chat.whatsapp.com/", "→",
}

def main() -> int:
    with PATH.open() as f:
        data = json.load(f)

    written = 0
    untouched = 0
    missing_keys: list[str] = []

    for key, entry in data["strings"].items():
        loc = entry.setdefault("localizations", {})
        if key in LITERAL_KEYS:
            loc["fr"] = {"stringUnit": {"state": "translated", "value": key}}
            untouched += 1
            continue
        fr_value = FR.get(key)
        if fr_value is None:
            missing_keys.append(key)
            # Fall back to EN value as last resort.
            en = loc.get("en", {}).get("stringUnit", {}).get("value") or key
            loc["fr"] = {"stringUnit": {"state": "needs_review", "value": en}}
            continue
        loc["fr"] = {"stringUnit": {"state": "translated", "value": fr_value}}
        written += 1

    with PATH.open("w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"translated:  {written}")
    print(f"literal:     {untouched}")
    print(f"missing:     {len(missing_keys)}")
    if missing_keys:
        print("missing keys (first 30):")
        for k in missing_keys[:30]:
            print(f"  {k}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
